name: Build and Push Docker Image to DockerHub - ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_URL: ${{ secrets.DB_URL }}
        envkey_COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
        envkey_ACCESS_TOKEN_PRIVATE_KEY_BASE64: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY_BASE64 }}
        envkey_ACCESS_TOKEN_PUBLIC_KEY_BASE64: ${{ secrets.ACCESS_TOKEN_PUBLIC_KEY_BASE64 }}
        envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        envkey_REFRESH_TOKEN_PRIVATE_KEY_BASE64: ${{ secrets.REFRESH_TOKEN_PRIVATE_KEY_BASE64 }}
        envkey_REFRESH_TOKEN_PUBLIC_KEY_BASE64: ${{ secrets.REFRESH_TOKEN_PUBLIC_KEY_BASE64 }}
        envkey_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        envkey_SENDER_IDENTITY: ${{ secrets.SENDER_IDENTITY }}
        envkey_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
        envkey_REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
        envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        file_name: .env
        fail_on_empty: false
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: | 
            greazleay/api-mbo
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}